SELECT 
FOOD_PRODUCT.CATEGORY, 
FOOD_PRODUCT.PRICE, 
FOOD_PRODUCT.PRODUCT_NAME

FROM 
FOOD_PRODUCT 
JOIN 
(SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
 FROM FOOD_PRODUCT 
 WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
 GROUP BY CATEGORY
) MAX_CATEGORY
ON MAX_CATEGORY.CATEGORY = FOOD_PRODUCT.CATEGORY AND FOOD_PRODUCT.PRICE = MAX_PRICE

ORDER BY MAX_PRICE DESC;