SELECT 
MONTH(START_DATE), 
CAR_ID,
COUNT(*) AS RECORDS

FROM
CAR_RENTAL_COMPANY_RENTAL_HISTORY 

WHERE 
DATE_FORMAT(START_DATE,"%Y-%m") IN ("2022-10","2022-09","2022-08")
AND
CAR_ID IN 
(SELECT CAR_ID 
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
 WHERE 
 DATE_FORMAT(START_DATE,"%Y-%m") IN ("2022-10","2022-09","2022-08")
 GROUP BY CAR_ID
 HAVING COUNT(*) >= 5
)

GROUP BY MONTH(START_DATE),CAR_ID
HAVING COUNT(*) > 0

ORDER BY MONTH(START_DATE), CAR_ID DESC;