-- 코드를 입력하세요
SELECT ICECREAM_INFO.FLAVOR 
FROM ICECREAM_INFO JOIN (SELECT FLAVOR FROM FIRST_HALF GROUP BY FLAVOR HAVING SUM(TOTAL_ORDER) > 3000) AS TOTAL ON ICECREAM_INFO.FLAVOR = TOTAL.FLAVOR
WHERE ICECREAM_INFO.INGREDIENT_TYPE = "fruit_based";