SELECT CAR_RENTAL_COMPANY_CAR.CAR_ID, CAR_RENTAL_COMPANY_CAR.CAR_TYPE, TRUNCATE(DAILY_FEE * 30 * (100-DISCOUNT_RATE)/100,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN
ON CAR_RENTAL_COMPANY_CAR.CAR_TYPE = CAR_RENTAL_COMPANY_DISCOUNT_PLAN.CAR_TYPE
JOIN (
SELECT 
CAR_ID,
SUM(TEST) AS TSUM
FROM
(
    SELECT CAR_ID, IF(START_DATE < "2022-11-01" AND END_DATE < "2022-11-01" OR START_DATE > "2022-11-30" AND END_DATE > "2022-11-30", 0, 1) AS TEST
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
) AS TB1
GROUP BY CAR_ID
) AS ABLE
ON ABLE.CAR_ID = CAR_RENTAL_COMPANY_CAR.CAR_ID
WHERE DURATION_TYPE = "30일 이상" AND TSUM = 0 AND TRUNCATE(DAILY_FEE * 30 * (100-DISCOUNT_RATE)/100,0) >= 500000 AND TRUNCATE(DAILY_FEE * 30 * (100-DISCOUNT_RATE)/100,0) < 2000000 AND CAR_RENTAL_COMPANY_CAR.CAR_TYPE IN ("SUV","세단")
ORDER BY FEE DESC, CAR_RENTAL_COMPANY_CAR.CAR_TYPE, CAR_RENTAL_COMPANY_CAR.CAR_ID DESC;

