SELECT C.CAR_ID, C.CAR_TYPE, TRUNCATE(C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING SUM(
        IF(
            (START_DATE > '2022-11-30' OR END_DATE < '2022-11-01'),
            0,
            1
        )
    ) = 0
) R ON C.CAR_ID = R.CAR_ID
WHERE D.DURATION_TYPE = '30일 이상'
  AND C.CAR_TYPE IN ('SUV', '세단')
  AND TRUNCATE(C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100, 0) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;
