SELECT 
SIMPLE_ECOLI_DATA.YEAR, 
MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, 
ID

FROM
(SELECT YEAR(DIFFERENTIATION_DATE) AS "YEAR", MAX(SIZE_OF_COLONY) AS MAX_SIZE FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) AS MAX_SIZE_TABLE
JOIN
(SELECT YEAR(DIFFERENTIATION_DATE) AS "YEAR", SIZE_OF_COLONY, ID FROM ECOLI_DATA) AS SIMPLE_ECOLI_DATA
ON SIMPLE_ECOLI_DATA.YEAR = MAX_SIZE_TABLE.YEAR

ORDER BY SIMPLE_ECOLI_DATA.YEAR, YEAR_DEV;
