SELECT 
CAR_ID,
IF(SUM(TEST) = 0, "대여 가능", "대여중") AS AVAILABILITY
FROM
(
    SELECT CAR_ID, IF(START_DATE <= "2022-10-16" AND END_DATE >= "2022-10-16", 1, 0) AS TEST
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
) AS TB1
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;