SELECT DISTINCT CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID, IF(ABLE.T != 0,"대여중", "대여 가능") AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY JOIN
(
    SELECT CAR_ID,SUM(IF(START_DATE <= "2022-10-16" AND END_DATE >= "2022-10-16", 1, 0)) AS T
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    GROUP BY CAR_ID
) ABLE
ON CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID = ABLE.CAR_ID
ORDER BY CAR_ID DESC;