SELECT QUARTER, COUNT(*) AS ECOLI_COUNT
FROM
(
SELECT 
    CASE TRUNCATE((MONTH(DIFFERENTIATION_DATE)-1) / 3,0)
    WHEN 0 THEN "1Q"
    WHEN 1 THEN "2Q"
    WHEN 2 THEN "3Q"
    WHEN 3 THEN "4Q"
    END AS QUARTER
    FROM ECOLI_DATA 
) AS ORIGIN_TABLE
GROUP BY QUARTER
ORDER BY QUARTER;