SELECT 
AUTHOR.AUTHOR_ID, 
AUTHOR.AUTHOR_NAME, 
BOOK.CATEGORY, 
SUM(BOOK.PRICE * IFNULL(ZIP_BOOK_SALES.SUM_SALES, 0)) AS TOTAL_SALES

FROM
BOOK JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
LEFT JOIN (SELECT BOOK_ID, SUM(SALES) AS SUM_SALES FROM BOOK_SALES WHERE DATE_FORMAT(SALES_DATE,"%Y-%m") = "2022-01" GROUP BY BOOK_ID) AS ZIP_BOOK_SALES
ON ZIP_BOOK_SALES.BOOK_ID = BOOK.BOOK_ID

GROUP BY AUTHOR.AUTHOR_ID, CATEGORY

ORDER BY BOOK.AUTHOR_ID, BOOK.CATEGORY DESC;