SELECT 
REST_INFO.FOOD_TYPE,
REST_INFO.REST_ID,
REST_INFO.REST_NAME,
REST_INFO.FAVORITES

FROM 
REST_INFO
JOIN
(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) MAX_REST
ON REST_INFO.FOOD_TYPE = MAX_REST.FOOD_TYPE AND REST_INFO.FAVORITES = MAX_REST.MAX_FAV

ORDER BY REST_INFO.FOOD_TYPE DESC;