SELECT ID, FISH_NAME, MAX_LENGTH AS "LENGTH"
FROM
(SELECT FISH_NAME_INFO.FISH_TYPE AS "FISH_TYPE",FISH_NAME, MAX_LENGTH
FROM 
(SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH FROM FISH_INFO GROUP BY FISH_TYPE) AS T1
JOIN FISH_NAME_INFO
ON FISH_NAME_INFO.FISH_TYPE = T1.FISH_TYPE
) AS GG
JOIN FISH_INFO ON MAX_LENGTH = FISH_INFO.LENGTH AND GG.FISH_TYPE = FISH_INFO.FISH_TYPE
ORDER BY ID;
;
